POST http://localhost:8080/api/pedidos
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 2,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 4,
            "quantidade": 4
        }
    ]
} 